[tox]
envlist = py312
skipsdist = true

[testenv]
deps =
    pytest
    httpx
    fastapi
    sqlalchemy
    pydantic
    pydantic-settings
    python-dotenv
    psycopg2-binary
    email-validator
    passlib[bcrypt]
    pytest-cov
commands =
    pytest src/ -v --cov=src --cov-report=xml

[pytest]
pythonpath = .
testpaths = src
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    integration: testes de integracao com API e banco em container
