"""criar_tabela_pedidos_e_associativa

Revision ID: 0188d64a109d
Revises: 104214f51d04
Create Date: 2026-05-12 00:56:51.634732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0188d64a109d'
down_revision = '104214f51d04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metodo_pagamento', sa.String(length=50), nullable=False),
    sa.Column('preco_total', sa.Float(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido_cliente_produtos',
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_cliente.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('pedido_id', 'produto_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido_cliente_produtos')
    op.drop_table('pedidos_cliente')
    # ### end Alembic commands ###
