"""criar_tabela_pedidos_e_associativa

Revision ID: 0188d64a109d
Revises: 104214f51d04
Create Date: 2026-05-12 00:56:51.634732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0188d64a109d'
down_revision = '104214f51d04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('complemento', sa.String(length=255), nullable=True),
    sa.Column('bairro', sa.String(length=255), nullable=False),
    sa.Column('cidade', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('imagem', sa.String(length=500), nullable=True),
    sa.Column('abertura', sa.Time(), nullable=False),
    sa.Column('fechamento', sa.Time(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('endereco_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['endereco_id'], ['enderecos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metodo_pagamento', sa.String(length=50), nullable=False),
    sa.Column('preco_total', sa.Float(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('preco_combo', sa.Float(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('esta_ativo', sa.Boolean(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('imagem', sa.String(length=500), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_categoria'), 'produtos', ['categoria'], unique=False)
    op.create_index(op.f('ix_produtos_nome'), 'produtos', ['nome'], unique=False)
    op.create_table('pedido_produtos',
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('pedido_id', 'produto_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido_produtos')
    op.drop_index(op.f('ix_produtos_nome'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_categoria'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_table('pedidos')
    op.drop_table('unidades')
    op.drop_table('enderecos')
    # ### end Alembic commands ###