"""migrando todas as tabela

Revision ID: 104214f51d04
Revises: 0002_create_tables
Create Date: 2026-05-11 22:56:52.902290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104214f51d04'
down_revision = '0002_create_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enderecos_id'), table_name='enderecos')
    op.drop_index(op.f('ix_permissoes_id'), table_name='permissoes')
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.drop_index(op.f('ix_unidades_id'), table_name='unidades')
    op.drop_index(op.f('ix_users_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_unidades_id'), 'unidades', ['id'], unique=False)
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    op.create_index(op.f('ix_permissoes_id'), 'permissoes', ['id'], unique=False)
    op.create_index(op.f('ix_enderecos_id'), 'enderecos', ['id'], unique=False)
    # ### end Alembic commands ###