"""novas_tabelas

Revision ID: 3c35161418b2
Revises: 8e8c0d37723b
Create Date: 2026-05-13 23:27:32.596788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c35161418b2'
down_revision = '8e8c0d37723b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('pontos_fidelidade', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formas_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('mesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('livre', 'ocupada', name='status_mesa'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('preparando', 'entregue', 'cancelado', name='status_pedido'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcategorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('forma_pagamento_id', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('taxas', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['forma_pagamento_id'], ['formas_pagamento.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto_variacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('normal', 'combo', name='tipo_variacao'), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_combo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('label_combo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('variacao_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['variacao_id'], ['produto_variacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adicionais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_pedido_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['item_pedido_id'], ['itens_pedido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('produtos', sa.Column('imagem_url', sa.String(length=500), nullable=True))
    op.add_column('produtos', sa.Column('ativo', sa.Boolean(), nullable=False))
    op.add_column('produtos', sa.Column('subcategoria_id', sa.Integer(), nullable=False))
    op.alter_column('produtos', 'descricao',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_produtos_categoria'), table_name='produtos')
    op.drop_constraint(op.f('produtos_unidade_id_fkey'), 'produtos', type_='foreignkey')
    op.create_foreign_key(None, 'produtos', 'subcategorias', ['subcategoria_id'], ['id'])
    op.drop_column('produtos', 'observacao')
    op.drop_column('produtos', 'categoria')
    op.drop_column('produtos', 'esta_ativo')
    op.drop_column('produtos', 'preco_combo')
    op.drop_column('produtos', 'preco')
    op.drop_column('produtos', 'unidade_id')
    op.drop_column('produtos', 'imagem')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('imagem', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('produtos', sa.Column('unidade_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('produtos', sa.Column('preco', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('produtos', sa.Column('preco_combo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('produtos', sa.Column('esta_ativo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('produtos', sa.Column('categoria', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('produtos', sa.Column('observacao', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'produtos', type_='foreignkey')
    op.create_foreign_key(op.f('produtos_unidade_id_fkey'), 'produtos', 'unidades', ['unidade_id'], ['id'])
    op.create_index(op.f('ix_produtos_categoria'), 'produtos', ['categoria'], unique=False)
    op.alter_column('produtos', 'descricao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('produtos', 'subcategoria_id')
    op.drop_column('produtos', 'ativo')
    op.drop_column('produtos', 'imagem_url')
    op.drop_table('adicionais')
    op.drop_table('itens_pedido')
    op.drop_table('produto_variacoes')
    op.drop_table('pedido_pagamento')
    op.drop_table('subcategorias')
    op.drop_table('pedidos')
    op.drop_table('mesas')
    op.drop_table('formas_pagamento')
    op.drop_table('clientes')
    op.drop_table('categorias')
    # ### end Alembic commands ###