"""corrige_tabela_adicionais

Revision ID: 68aba97f921c
Revises: 1f32fc4f41bc
Create Date: 2026-05-18 00:20:44.094175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68aba97f921c'
down_revision = '1f32fc4f41bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto_adicionais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('unidades', 'endereco_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unidades', 'endereco_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('produto_adicionais')
    # ### end Alembic commands ###