"""add_status_pedidos

Revision ID: 7db2835f4a6f
Revises: 0188d64a109d
Create Date: 2026-05-13 01:11:18.109801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db2835f4a6f'
down_revision = '0188d64a109d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('status', sa.String(length=50), server_default='Recebido', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'status')
    # ### end Alembic commands ###