"""migrando as novas tabelas

Revision ID: 8e8c0d37723b
Revises: 104214f51d04
Create Date: 2026-05-13 01:32:59.317244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8c0d37723b'
down_revision = '104214f51d04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
