"""adiciona campo ativo em clientes

Revision ID: 9abe9133cc7d
Revises: 5c8d2c0c1a8e
Create Date: 2026-05-18 14:14:51.517006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9abe9133cc7d'
down_revision = '5c8d2c0c1a8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Olha o server_default='true' adicionado aqui no final desta linha:
    op.add_column('clientes', sa.Column('ativo', sa.Boolean(), nullable=False, server_default='true'))
    
    op.alter_column('unidades', 'endereco_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unidades', 'endereco_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('clientes', 'ativo')
    # ### end Alembic commands ###