"""many to many usuario permissao

Revision ID: cfc8005bd633
Revises: e3f888786ddd
Create Date: 2026-05-14 01:59:12.882595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfc8005bd633'
down_revision = 'e3f888786ddd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_permissoes',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('permissao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permissao_id'], ['permissoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'permissao_id')
    )
    op.drop_constraint(op.f('fk_usuarios_permissao_id'), 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'permissao_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('permissao_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_usuarios_permissao_id'), 'usuarios', 'permissoes', ['permissao_id'], ['id'])
    op.drop_table('usuario_permissoes')
    # ### end Alembic commands ###