"""remove tabelas deletadas

Revision ID: e3f888786ddd
Revises: 3c35161418b2
Create Date: 2026-05-14 01:44:34.566450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f888786ddd'
down_revision = '3c35161418b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adicionais')
    op.drop_table('itens_pedido')
    op.drop_table('pedido_pagamento')
    op.drop_table('pedidos')
    op.drop_table('mesas')
    op.drop_table('formas_pagamento')
    op.add_column('clientes', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('clientes', sa.Column('data_cadastro', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'data_cadastro')
    op.drop_column('clientes', 'email')
    op.create_table('formas_pagamento',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('formas_pagamento_pkey')),
    sa.UniqueConstraint('nome', name=op.f('formas_pagamento_nome_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('pedido_pagamento',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('forma_pagamento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('taxas', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['forma_pagamento_id'], ['formas_pagamento.id'], name=op.f('pedido_pagamento_forma_pagamento_id_fkey')),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], name=op.f('pedido_pagamento_pedido_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pedido_pagamento_pkey'))
    )
    op.create_table('itens_pedido',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('variacao_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('observacao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preco_unitario', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], name=op.f('itens_pedido_pedido_id_fkey')),
    sa.ForeignKeyConstraint(['variacao_id'], ['produto_variacoes.id'], name=op.f('itens_pedido_variacao_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('itens_pedido_pkey'))
    )
    op.create_table('mesas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('livre', 'ocupada', name='status_mesa'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('mesas_pkey'))
    )
    op.create_table('adicionais',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_pedido_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_pedido_id'], ['itens_pedido.id'], name=op.f('adicionais_item_pedido_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('adicionais_pkey'))
    )
    op.create_table('pedidos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hora', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('mesa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('preparando', 'entregue', 'cancelado', name='status_pedido'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('pedidos_cliente_id_fkey')),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], name=op.f('pedidos_mesa_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pedidos_pkey'))
    )
    # ### end Alembic commands ###